print("cmd/crtl Save")
print("Click on the branch icon")
print("under changes click on + sign to stage")
print("Write your commit message")
print("Click Commit")
print("click on 3 dots and then click push")
